mlp-mixer discriminator
ardarslan/neural-human-rendering pull request #31
Opened 2022-05-20 17:26 UTC by tancredeguillou

2022-05-21 20:15 UTC, ardarslan commented on src/evaluation_metrics.py
> +    if cfg["dataset_type"] == "face" or cfg["dataset_type"] == "face_reconstruction"):
For face reconstruction we should report ssim and lpips scores.

2022-05-21 20:16 UTC, ardarslan commented on src/model/discriminator/mlp_mixer.py
> +def MLPMixerDiscrimator(cfg, positional_encoding=False):
This should be MLPMixerDiscriminator

2022-05-21 20:16 UTC, ardarslan commented on src/utils.py
> +            ModelClass = MLPMixerDiscrimator
This also should be MLPDiscriminator

2022-05-21 20:17 UTC, ardarslan commented on src/utils.py
> +            ModelClass = MLPMixerDiscrimator
This also should be MLPMixerDiscriminator

2022-05-21 20:17 UTC, ardarslan requested changes
I added some comments. Thanks for the PR!

2022-05-24 09:36 UTC, tancredeguillou reviewed
Changes updated

2022-05-26 07:37 UTC, ardarslan approved these changes

2022-05-26 07:37 UTC, merged